apiVersion: v1
kind: Pod

metadata:
  name: web-pod
  labels:
    app: web
    environment: dev
    tier: frontend

spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
